---
apiVersion: v2
appVersion: stable
description: Factorio dedicated steam game server
name: factorio
version: 1.2.2
kubeVersion: ">=1.16.0-0"
keywords:
  - factorio
  - steam
home: https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/factorio
icon: https://factorio.com/static/img/factorio-wheel.png
sources:
  - https://github.com/factoriotools/factorio-docker
maintainers:
  - name: Truxnell
    email: nat@natallan.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 0.2.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Use bjw-s common chart.
