---
apiVersion: v2
appVersion: stable
description: Factorio dedicated steam game server
name: factorio
version: 4.2.0
deprecated: true
kubeVersion: ">=1.19.0-0"
keywords:
  - factorio
  - steam
home: https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/factorio
icon: https://factorio.com/static/img/factorio-wheel.png
sources:
  - https://github.com/factoriotools/factorio-docker
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 1.5.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
