---
apiVersion: v2
appVersion: 1.0.0
description: Searx is a privacy-respecting, hackable metasearch engine
name: searx
version: 7.0.0
deprecated: true
kubeVersion: ">=1.19.0-0"
keywords:
  - searx
  - search engine
  - privacy
home: https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/searx
icon: https://github.com/searx/searx/blob/master/searx/static/themes/simple/img/logo_searx_a.png?raw=true
sources:
  - https://github.com/searx/searx
  - https://searx.github.io/searx/
  - https://hub.docker.com/r/searx/searx
maintainers:
  - name: auricom
    email: k8s-at-home@xpander.eml.cc
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 0.2.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Use bjw-s common chart.
