---
apiVersion: v2
appVersion: v0.20
description: DNS proxy as ad-blocker for local network
name: blocky
version: 13.0.2
deprecated: true
kubeVersion: ">=1.19.0-0"
keywords:
  - blocky
  - adblock
  - dns
home: https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/blocky
icon: https://github.com/0xERR0R/blocky/raw/master/docs/blocky.svg?sanitize=true
sources:
  - https://github.com/0xERR0R/blocky
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 0.2.2
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.3.13
    condition: redis.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `redis` chart dependency to version 17.3.11
