---
apiVersion: v2
appVersion: v0.20.2186
description: API Support for your favorite torrent trackers
name: jackett
version: 13.0.0
kubeVersion: ">=1.19.0-0"
keywords:
  - jackett
  - torrent
home: https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/jackett
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/jackett-banner.png
sources:
  - https://github.com/Jackett/Jackett
  - https://github.com/k8s-at-home/container-images
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 1.0.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Use bjw-s common chart.
    - kind: changed
      description: Upgraded app to 0.20.2186.
