---
apiVersion: v2
appVersion: 1.26.0
description: Vaultwarden is a Bitwarden compatable server in Rust
name: vaultwarden
version: 8.1.1
deprecated: true
kubeVersion: ">=1.19.0-0"
keywords:
  - Vaultwarden
  - bitwardenrs
home: "https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/vaultwarden"
icon: "https://sesoodan.sirv.com/bitwarden_rs.png"
sources:
  - https://github.com/dani-garcia/vaultwarden
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 0.2.2
  - name: mariadb
    version: 11.4.5
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: postgresql
    version: 12.1.13
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `mariadb` chart dependency to version 11.4.2
    - kind: changed
      description: Upgraded `postgresql` chart dependency to version 12.1.6
