---
apiVersion: v2
appVersion: 8.2.2
description: Fully configurable Zwave to MQTT Gateway and Control Panel
name: zwavejs2mqtt
version: 6.0.0
kubeVersion: ">=1.19.0-0"
keywords:
  - zwave
  - mqtt
  - home-assistant
home: https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/zwavejs2mqtt
icon: https://raw.githubusercontent.com/zwave-js/zwavejs2mqtt/v4.0.0/static/logo.png
sources:
  - https://github.com/zwave-js/zwavejs2mqtt
  - https://hub.docker.com/r/zwavejs/zwavejs2mqtt
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 0.2.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
     description: Upgraded `appVersion` to 8.2.2
    - kind: changed
     description: Use bjw-s common chart.
