---
apiVersion: v2
appVersion: 2.6.0
description: Server error pages in the docker image
name: error-pages
version: 3.0.0
kubeVersion: ">=1.19.0-0"
keywords:
  - traefik
  - error-pages
home: https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/error-pages
icon: https://hsto.org/webt/rm/9y/ww/rm9ywwx3gjv9agwkcmllhsuyo7k.png
sources:
  - https://github.com/tarampampam/error-pages
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 1.0.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Use bjw-s common chart.
