---
apiVersion: v2
appVersion: 0.20.0
description: The to-do app to organize your life
name: vikunja
version: 9.0.0
deprecated: true
keywords:
  - vikunja
  - to-do
  - tasks
  - calendar
  - kanban
home: https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/vikunja
icon: https://vikunja.io/images/vikunja-logo.svg
sources:
  - https://kolaente.dev/vikunja/api
  - https://kolaente.dev/vikunja/frontend
  - https://hub.docker.com/r/vikunja/api
  - https://hub.docker.com/r/vikunja/frontend
  - https://vikunja.io/docs/
maintainers:
  - name: auricom
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 0.2.2
  - name: postgresql
    version: 12.0.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `appVersion` to 0.20.0
    - kind: changed
      description: Use bjw-s common chart.
