---
apiVersion: v2
appVersion: 0.7.4
description: A self-hosted, ad-free, privacy-respecting metasearch engine
name: whoogle
version: 5.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - whoogle
  - search
  - open source
  - privacy
home: https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/whoogle
icon: https://raw.githubusercontent.com/benbusby/whoogle-search/develop/docs/banner.png
sources:
  - https://github.com/benbusby/whoogle-search
maintainers:
  - name: FlipEnergy
    email: dennis.zhang.nrg@gmail.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 1.0.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `appVersion` to 0.7.4
    - kind: changed
      description: Use bjw-s common chart.
