---
apiVersion: v2
appVersion: v3.2.2
description: Speedtest Exporter made in python using the official speedtest bin
name: speedtest-exporter
version: 7.0.0
deprecated: true
kubeVersion: ">=1.19.0-0"
keywords:
  - speedtest-exporter
  - speedtest
home: https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/speedtest-exporter
sources:
  - https://github.com/MiguelNdeCarvalho/speedtest-exporter/
maintainers:
  - name: onedr0p
    email: devin.kray@gmail.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 0.2.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Use bjw-s common chart.
