---
apiVersion: v2
appVersion: v3.2.2
description: Speedtest Exporter made in python using the official speedtest bin
name: speedtest-exporter
version: 8.2.0
deprecated: true
kubeVersion: ">=1.19.0-0"
keywords:
  - speedtest-exporter
  - speedtest
home: https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/speedtest-exporter
sources:
  - https://github.com/MiguelNdeCarvalho/speedtest-exporter/
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 1.5.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.4.0
