---
apiVersion: v2
appVersion: version-2.5.290
description: Make documentation a joy to write using Wiki.js's beautiful and intuitive interface!
name: wikijs
version: 8.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - wiki
  - wikijs
home: https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/wikijs
icon: https://static.requarks.io/logo/wikijs-butterfly.svg
sources:
  - https://hub.docker.com/r/linuxserver/wikijs/
  - https://github.com/Requarks/wiki
maintainers:
  - name: rolfberkenbosch
    email: rolf@berkenbosch.nl
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 1.0.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `appVersion` to version-2.5.290
    - kind: changed
      description: Use bjw-s common chart.
