---
apiVersion: v2
appVersion: 5.22.4
description: Ghost is a blogging and publishing software
name: ghost
version: 4.0.0
kubeVersion: ">=1.19.0-0"
keywords:
  - ghost
  - blogging
home: https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/ghost
icon: https://ghost.org/images/logos/logo-black-1.png
sources:
  - https://github.com/TryGhost/Ghost
  - https://github.com/TryGhost/Ghost-CLI
maintainers:
  - name: samip5
    email: sm+k8s-at-home+git@samip.fi
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 0.2.2
  - name: mariadb
    version: 11.3.3
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `appVersion` to 5.22.4
    - kind: changed
      description: Use bjw-s common chart.
    
