---
apiVersion: v2
appVersion: 1.28.1
description: Bridges events and allows you to control your Zigbee devices via MQTT
name: zigbee2mqtt
version: 11.0.0
kubeVersion: ">=1.19.0-0"
keywords:
  - zigbee
  - mqtt
  - home-assistant
home: https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/zigbee2mqtt
icon: https://www.zigbee2mqtt.io/logo.png
sources:
  - https://github.com/Koenkk/zigbee2mqtt
maintainers:
  - name: masantiago
    email: miguelangel.santiago@hotmail.com
  - name: bjw-s
    email: me@bjw-s.dev
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 1.0.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `appVersion` to 1.28.1
    - kind: changed
      description: Use bjw-s common chart.
