---
apiVersion: v2
appVersion: v7.2.94
description: Ubiquiti Network's Unifi Controller
name: unifi
version: 8.1.1
deprecated: true
keywords:
  - ubiquiti
  - unifi
home: https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/unifi
icon: https://prd-www-cdn.ubnt.com/static/favicon-152.png
sources:
  - https://github.com/jacobalberty/unifi-docker
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 0.2.2
  - name: mongodb
    version: 13.6.7
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `mongodb` chart dependency to version 13.6.2
