---
apiVersion: v2
appVersion: 3.7.0-apache
description: A Personal Relationship Management tool to help you organize your social life
name: monica
version: 10.1.1
deprecated: true
kubeVersion: ">=1.19.0-0"
keywords:
  - crm
home: https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/monica
icon: https://pbs.twimg.com/profile_images/951820722191720450/mtCNuIXX.jpg
sources:
  - https://github.com/monicahq/monica
  - https://hub.docker.com/_/monica
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 0.2.2
  - name: mariadb
    version: 11.4.5
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `mariadb` chart dependency to version 11.4.2
