---
apiVersion: v2
appVersion: v0.10.7
description: Dendrite Matrix Homeserver
name: dendrite
version: 9.1.0
kubeVersion: ">=1.20.0-0"
deprecated: true
keywords:
  - dendrite
  - matrix
  - homeserver
  - monolith
  - federation
  - polylith
home: https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/dendrite
maintainers:
  - name: samip5
    url: https://github.com/samip5
sources:
  - https://github.com/matrix-org/dendrite
  - https://github.com/matrix-org/dendrite/tree/master/build/docker
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 0.2.2
  - name: nats
    version: 0.18.2
    repository: https://nats-io.github.io/k8s/helm/charts/
    condition: nats.enabled
  # Client API
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 0.2.2
    alias: clientapi
    condition: dendrite.polylithEnabled
  # Media API
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 0.2.2
    alias: mediaapi
    condition: dendrite.polylithEnabled
  # Sync API
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 0.2.2
    alias: syncapi
    condition: dendrite.polylithEnabled
  # Room Server
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 0.2.2
    alias: roomserver
    condition: dendrite.polylithEnabled
  # Federation API
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 0.2.2
    alias: federationapi
    condition: dendrite.polylithEnabled
  # Key Server
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 0.2.2
    alias: keyserver
    condition: dendrite.polylithEnabled
  # User API
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 0.2.2
    alias: userapi
    condition: dendrite.polylithEnabled
  # App Service API
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 0.2.2
    alias: appserviceapi
    condition: dendrite.polylithEnabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `nats` chart dependency to version 0.18.2
    - kind: changed
      description: Added deprecation information.
